# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development: &development
  adapter: mysql2
  encoding: utf8
  database: cms_dev
  pool: 5
  username: root
  timeout: 5000
  host: localhost
test:
  <<: *development
  database: cms_test

production:
  <<: *development
  database: cms

